import streamlit as st
import datetime
import requests
import sys

BASE_URL = "http://localhost:8000"

st.set_page_config(
    page_title="🌍 Travel Planner Agentic Application",
    page_icon="🌍",
    layout="centered",
    initial_sidebar_state="expanded",
)

st.title("🌍 Travel Planner Agentic Application")

# initialize chat history
if 'messages' not in st.session_state:
    st.session_state.messages = []

st.header("How can I assist you with your travel plans today?")

with st.form():
    submit_button = st.form_submit_button(label="Send")
    user_input = st.text_input("User Input", placeholder="e.g., Plan a trip to Goa for 5 days with a budget of Rs.10000")



if submit_button and user_input.strip():
    try:
        # Show user input in the chat
        # Show thinking spinner while backend process
        with st.spinner("Bot is thinking..."):
            payload = {'question' : user_input}
            response = requests.post(f"{BASE_URL}/query", json=payload)
        
        if response.status_code == 200:
            answer = response.json().get("answer", "Sorry, I couldn't get an answer.")
            markdown_content = f""" # 🌍 AI Trip Plan
            
            # **Generated: ** {datetime.datetime.now().strftime("%Y-%m-%d at %H:%M")}
            # **Created by : ** Atriyo's Travel Agent

            ---
            
            {answer}

            ---

            *This response is generated by an AI travel agent using real-time data from the internet. The information provided is based on the latest available data and may be subject to change. Always verify details before making any travel arrangements.*
            """
    
    except Exception as e:
        raise f"The response failed due to {str(e)}"